package com.druk.llamacpp

/**
 * An interface for receiving newly generated tokens during text generation with llama.cpp.
 */
interface LlamaGenerationCallback {

    /**
     * Called whenever new tokens are generated by the language model.
     *
     * @param newString A byte array represented current response, encoded using UTF-8.
     */
    fun newString(newString: ByteArray)
}